FROM itzcrazykns1337/perplexica:latest

# Install Ollama
RUN curl -fsSL https://ollama.com/install.sh | sh

COPY ollama.service.d/override.conf /etc/systemd/system/ollama.service.d/override.conf

RUN systemctl start ollama
RUN ollama pull gemma3:latest
RUN ollama pull nomic-embed-text:latest

EXPOSE 3000 8080 11434

CMD ["/home/perplexica/entrypoint.sh"]
